# Endpoints SOAP
soap.java.url=http://209.145.48.25:8091/ROOT/CoreBancarioWS
soap.dotnet.url=http://209.145.48.25:8092/CoreBancarioWS

# Endpoints REST
rest.java.url=http://209.145.48.25:8090/resources/corebancario
rest.dotnet.url=http://209.145.48.25:8093/resources/corebancario

# Timeouts (ms)
timeout.connection=5000
timeout.read=5000